name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - '**.gif'
      - '**.jpg'
      - '**.png'
      - '**.webp'
      - ".gitignore"
      - ".editorconfig"
      - ".swift-format"
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.5"

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Create build configuration
        run: cp Configuration/Settings.xcconfig.example Configuration/Settings.xcconfig

      - name: Build
        run: make build

      - name: Test
        run: make test TEST_DESTINATION='platform=iOS Simulator,name=iPhone 17 Pro,OS=26.5'
